<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	 <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Notification.Wpf" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LTS.Application\LTS.Application.csproj" />
    <ProjectReference Include="..\LTS.Common\LTS.Common.csproj" />
    <ProjectReference Include="..\LTS.Data\LTS.Data.csproj" />
  </ItemGroup>

</Project>
